trigger:
- master  # A pipeline será acionada em commits na branch master

pool:
  vmImage: ubuntu-latest

steps:
# Instalar Java 21 manualmente
- script: |
    sudo apt update
    sudo apt install -y openjdk-21-jdk
    java -version
  displayName: 'Instalar Java 21'

# Executar Maven clean package
- script: |
    mvn clean package
  displayName: 'Build com Maven'

# Configurar Git com suas credenciais
- script: |
    git config --global user.email "heitorbrunini.ifpb@gmail.com"
    git config --global user.name "heitorbrunini"
  displayName: 'Configurar Git'

# Adicionar os arquivos gerados no target/ ao controle de versão
- script: |
    git add target/*
    git commit -m "Commit automático: arquivos gerados pelo Maven"
  displayName: 'Commit dos arquivos gerados'

# Fazer push das mudanças para o repositório
- script: |
    git remote set-url origin https://$(GITHUB_PAT)@github.com/seu-usuario/seu-repositorio.git
    git push origin master
  displayName: 'Push dos arquivos para o repositório'
  env:
    GITHUB_PAT: $(GITHUB_PAT)
