trigger:
- master  # A pipeline será acionada em commits na branch master

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    sudo apt update
    sudo apt install -y openjdk-21-jdk
    sudo update-alternatives --set java /usr/lib/jvm/java-21-openjdk-amd64/bin/java
  displayName: 'Instalar e definir Java 21 como padrão'

- script: |
    echo "JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64" | sudo tee -a /etc/environment
    export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
    echo $JAVA_HOME
    java -version
    

# Verificar se Java e Maven estão configurados corretamente
- script: |
    echo $JAVA_HOME
    java -version
    mvn -version
    printenv
  displayName: 'Verificar versão do Java e Maven'
  

# Executar Maven clean package
- script: |
    cd demo
    mvn clean package
  displayName: 'Build com Maven'

# Configurar Git com suas credenciais
- script: |
    git config --global user.email "heitorbrunini.ifpb@gmail.com"
    git config --global user.name "heitorbrunini"
  displayName: 'Configurar Git'

# Adicionar os arquivos gerados no target/ ao controle de versão
- script: |
    git add .
    git diff --staged --quiet || git commit -m "Commit automático: arquivos gerados pelo Maven"
  displayName: 'Commit dos arquivos gerados'

# Fazer push das mudanças para o repositório
- script: |
    git remote set-url origin https://$(GITHUB_PAT)@github.com/heitorbrunini/demo
    git push origin master
  displayName: 'Push dos arquivos para o repositório'
  env:
    GITHUB_PAT: $(GITHUB_PAT)
