trigger:
- master  # A pipeline será acionada em commits na branch master

pool:
  vmImage: ubuntu-latest

steps:

# Verificar se Java e Maven estão configurados corretamente
- script: |
    java -version
    mvn -version
  displayName: 'Verificar versão do Java e Maven'
  

# Executar Maven clean package
- script: |
    cd demo
    mvn clean package
  displayName: 'Build com Maven'

# Configurar Git com suas credenciais
- script: |
    git config --global user.email "heitorbrunini.ifpb@gmail.com"
    git config --global user.name "heitorbrunini"
  displayName: 'Configurar Git'

# Adicionar os arquivos gerados no target/ ao controle de versão
- script: |
    git add .
    git diff --staged --quiet || git commit -m "Commit automático: arquivos gerados pelo Maven"
  displayName: 'Commit dos arquivos gerados'

# Fazer push das mudanças para o repositório
- script: |
    git remote set-url origin https://$(GITHUB_PAT)@github.com/heitorbrunini/demo
    git push origin master
  displayName: 'Push dos arquivos para o repositório'
  env:
    GITHUB_PAT: $(GITHUB_PAT)
